### PR TITLE
gruntfile: clean collection after unzipping

### PR DESCRIPTION
**Pull request by kiike**
During the packaging work for Nix, we noticed that the `wget` task would always try downloading the collections file, even though we downloaded it to the cache location. After some digging, it looks like cleaning the downloaded file before the download will just do that.

If we run the `clean:collection` task after unzipping, we allow downloading the file manually into the cache directory so that the unzip task doesn't try downloading it again. That is especially beneficial on NixOS, as the dependencies should be cached before running the build.

### CODE REVIEW

**Comment by cavearr** [comment]
Great improvements for the packager , thanks!

In other way i'll try to try it on OSX , but i have errors (i'm novice with nix), i do this steps:

1) Clone nixpkg repo
2) checkout fern/icestudio
3)  Go to icestudio dir
4) Excecute nix-build package.nix

but i receive the error error: cannot evaluate a function that has an argument without a value ('fetchurl')
       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/language/constructs.html#functions.
       at /Users/carl/work/nixpkgs/pkgs/by-name/ic/icestudio/package.nix:1:69:
            1| { lib, stdenv, fetchFromGitHub, buildNpmPackage, nwjs, makeWrapper, fetchurl
             |                                                                     ^
            2| , python3, python3Packages, }:

I'm asking you if there is a beginners guide or some documentation that you recomended.

**Comment by kiike** [comment]
Thanks for wanting to try it!

>     Clone nixpkg repo
>     checkout fern/icestudio
>     Go to icestudio dir
>     Excecute nix-build package.nix

The last step is not what you need to run. From the root of the nixpkgs repo, and after checking out the `fern/icestudio` branch, run `nix-build -A icestudio`. This means "build the attribute `icestudio`" which, sure, is a package for us, but for the package manager is an attribute.

After a hopefully successful build, a `result` directory will appear. You can then run `./result/bin/icestudio`.

For documentation i'd check out nix.dev, like https://nix.dev/tutorials/packaging-existing-software.html#your-first-package.

Regarding this PR, it actually contains an error due to my misunderstanding of the clean:collection task. Although it says that it removes the previously downloaded collection, it removes both the downloaded collection and the unzipped collection, so the build will not be correct. May I ask to reopen this PR? I'd like to add a fix. Thanks!

**Comment by cavearr** [comment]
The Merge is reverted!

**Comment by cavearr** [comment]
And dont worry was my fault, i'm not remember well what "clean collections" do and i don't check in deep.

**Comment by cavearr** [comment]
Hi! i'm trying to build in osx, but several errors appears, one of them and i think the first to start (others, i think are  promoted by this one) in nixpkgs osx is not supported by nwjs pkg:

```
  error: Package ‘nwjs-0.88.0’ in /Users/carl/work/nixpkgs/pkgs/development/tools/nwjs/default.nix:141 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "i686-linux"
           "x86_64-linux"
         ]
```

i'll try to add support to this!

**Comment by kiike** [comment]
Thank you so much for trying it! We'll definitely use your help I think :smile:!

**Comment by cavearr** [comment]
Hello @kiike! i have managed to package in nix nwjs for osx!!! Tomorrow I'll try to pack icestudio! I'm learning a lot through the process with nwjs. I feel more comfortable with nix at every step :)

Captura de pantalla 2024-07-11 a las 22 41 59

**Comment by kiike** [comment]
Nice! I'm looking forward to hearing if the package works on macOS on aarch64!

**Comment by cavearr** [comment]
Hi @kiike ! 'm forking nixpkgs and launch the PR for nwjs support.

Then i'm trying to checkout in my fork to fern/icestudio but i don't find it, you move it? in wich branch is icestudio now? thanks!!

**Comment by kiike** [comment]
Hey @cavearr! Nice! I'm excited you are taking these steps :+1:! The branch is still active, but it lives in @jackleightcap's fork. So just add his remote. https://github.com/jleightcap/nixpkgs/ branch: fern/icestudio.

**Comment by cavearr** [comment]
Ou!! sorry!!  i'm fork from your PR and i not show it sorry! i have a PR for nwjs to the nixpkgs yesterday , in the afternoon or tomorror i'll do it to your fork (nwjs and icestudio).

Thanks again for your patience!

**Pull request merged**
