### PR TITLE
board: Olimex iCE40HX8K-EVB

### PR DESCRIPTION
**Pull request by brianredbeard**
This is the definition files for the open hardware Olimex iCE40HX8K-EVB.
This device features 4 40 pin breakouts (at 1mm pitch) as well as a 34
pin GPIO breakout at 2.54mm.  Programming is done via SPI at 3.3v though
the board utilizes 5V.  The breakout headers supply both 3.3 and 5v.

More information on the hardware can be found here:

Info page:
  https://www.olimex.com/Products/FPGA/iCE40/iCE40HX8K-EVB/open-source-hardware

Source repository with Gerbers / KiCAD definitions:
  https://github.com/OLIMEX/iCE40HX8K-EVB

Discussions about the hardware:
  https://www.olimex.com/forum/index.php?board=35.0

### CODE REVIEW

**Comment by Jesus89** [comment]
Great contribution @brianredbeard! Thanks!.

NOTE: I will hide this board in the menu until it is fully supported (I hope to get time to create a guide to add new boards in [apio](http://apiodoc.readthedocs.io/en/stable/) and Icestudio soon)

**Comment by zeroeth** [comment]
This board seems like a good opportunity to support a generic 'Arduino as SPI flasher' All the others seem to use ftdi, or a pi based flash program, or some stm32 bin to header packer. 

Olimex uses pc side program 'iceprogduino' and talks to a sketch on the arduino https://github.com/OLIMEX/iCE40HX1K-EVB/tree/master/programmer

This would allow anyone with a stm32 bluepill or spare arduino uno/feather/etc to use it as a programmer!

Similar approaches just to note: 
https://github.com/florolf/spi-flasher
https://github.com/ivanovp/blue_flash (made to write to the Olimex originally)
https://github.com/LowPowerLab/SPIFlash
https://github.com/nfd/spi-flash-programmer (includes Olimex example)

**Comment by x653** [comment]
Hi there,

how can I use icestudio, to programm Olimex iCE40HX8K-EVB?
Is the board supported?

**Comment by Obijuan** [comment]
This board is not yet supported. The first step is giving support in [Apio](https://github.com/FPGAwars/apio), which is the backend. Then the support in icestudio can be provided. Any help is welcome as we do not have the Olimex board

**Comment by ullbeking** [comment]
> This board seems like a good opportunity to support a generic 'Arduino as SPI flasher' All the others seem to use ftdi, or a pi based flash program, or some stm32 bin to header packer.

I am new to FPGA and I don't know what much of anything here means.  However your idea of "Arduino as SPI flasher" really interests me, as I am keen to explore the idea of this kind of device that is an SPI flasher.

**Pull request merged**
