### PR TITLE
Collection Manager plugin fixes

### PR DESCRIPTION
**Pull request by mSlider**
- Re-Fix Collection Manager for pick-up blocks (ex: icePLL blocks)
- Reduce Timeouts
- Hide blocks that there are put directly in the 1st level folder of the collection (In fact, there will not be put here)

As discussed here #563

### CODE REVIEW

**Comment by mSlider** [comment]
Thanks Juan!!!

Alex,
mSlider.com

**Comment by jojo535275** [comment]
Hola Juan and Alex,

Thanks for that new wip, i tested it and/
- the pick-up blox fix is ok! 
- The same for hidden blocks on the 1st level folder. A constraint that we may remove some day ;-). But lets forget that!

-Now, for the timeout trimming (1000 to 100) , we have a problem, now the CM take ages for loading (i tried with 20 collection an it is more than 5 min,then is stopped waiting :-)  ).

Using debugging (F12) and making a record on the performance tab, we see that one block is load every 100msec, and nothing other is processed during that time. !??
Capture11

**Comment by cavearr** [comment]
Hi @jomo @mSlider ! the loading its very easy to reduce, because for the moment always reload the collection, this weekend i'll go to do persistent ok? in this way only take time the first time you load it , or when you decide to reload.

**Comment by mSlider** [comment]
Hi Jo,
Meanwhile Carlos tweak the collection reloading, try to change this down to or near zero. (Lines 255 and 266) of IceGuiTree.js

And comment here the results.

image

**Comment by jojo535275** [comment]
Ok Alex, 
I will play a bit with these timeouts. 
Trying to see if there is something optimal/safe, that will be useful for the "collections reload" function as mentioned Carlos!
 
Thanks to all of you and enjoy the cold week-end !

**Comment by cavearr** [comment]
Hi! this timeouts i think dont be more faster the loading proccess, or yes maybe. This timeouts are used to wait for the indexation only. this could be replaced by promises, but with this prototype i didn't want to use it to maintain with simple javascript the code.

The problem of the loading proccess is because the proccess run over all of your directories, open de .ice files, load and interpret the .ice file (a floavour of json) to obtain the data.

This proccess depends of your machine (fast disk is the mos important).

For this, i think the only way to improve a lot this is doing the database  persistent. This is not complex thing, i dont do before because i'm experimenting in other project with other database than indexdb and i'm doubt if using it here (i'm discard yet the other option, we kept indexdb :) )

If you think some thing or have and better idea, discuss please!

**Comment by jojo535275** [comment]
Ok, in the 28 collections i was tryng to load, there was also the "Ice-block"! And as i mentioned  yesterday, these collection freezes the collection Manager! So i could have wait for a very long time! :-)

So after removing it, i tried the following timeout values (1000,100,10,1) and as Carlos just wrote it doesn't make any difference.
Every time my computer loads all the collection in about 8 seconds.
So, it is not so bad!

But if some day, we can reduce that time to 2 secs, with the method you mentioned Carlos, it will be better !
I'm always hunting for details that can break users inspiration :-)! 
After all, Fpga digital electronics design is a respectable ART ;-)

**Comment by jojo535275** [comment]
i know nothing about databases, 

But maybe we can gain something time if , at startup, it was possible to go twice trough the database.

- first time (very fast) for updating only the collection folders structure and the block names. (the necessary for updating )
- and second time for collecting all the rest (openning ice files, interpreting,...)  (8 sec)  . But this process time will ,hopefully, not be visible by the user !?

**Pull request merged**
