### PR TITLE
Support for ECP5 boards

### PR DESCRIPTION
**Pull request by mmicko**
Added ULX3S support for IceStudio, requires apio from develop branch (pull request https://github.com/FPGAwars/apio/pull/190 )

### CODE REVIEW

**Comment by agnunez** [comment]
I managed to install your pending pull request, both for apio and
icestudio, in order to test my ulx3s-85f. Apio works ok and I'm able to
build and upload, both in windows and linux. After having some issues with
npm install for icestudio, I managed also to create distro's for both
platforms 32 and 64 bits.
Problem is now that after launching icestudio, it warns that toolchain is
not installed, (don't know how to engage the working apio), and if I try to
install the toolchain, it doesn't find appropriate version (and will not
find your pull request version of apio). Any clue how to configure
icestudio to look for the already installed and working apio?

Thanks
@agnuca

**Comment by mmicko** [comment]
@agnunez Thanks for checking this. In order to make it able to use apio you actually to force icestudio to use this specific version.

I have used one on my branch, but revert it to previous version with :
https://github.com/mmicko/icestudio/commit/14e0ef38ffe6170abfbb18ef2c74844de8c3e8c8

so when just use next line to force it use that code (of change my name to FPGAwars when this get merged), otherwise it is using version from master.
'git+https://github.com/mmicko/apio.git@develop#egg=apio[' +

**Comment by Obijuan** [comment]
Thanks a lot Miodrag! :-)

**Comment by agnunez** [comment]
Thanks to both, I'm eager to use ice studio with ulx3s... only using apio.
Could not solve different python requirements to install both pull request
at once.

Congrats
@agnuca

**Pull request merged**
