### PR TITLE
ECP-5 Evaluation Board Added. 

### PR DESCRIPTION
**Pull request by benitoss**
Additionally I have solved the support for ECP5-LFE5UM and ECP5-LFE5UM5G models in Apio.
https://www.latticesemi.com/products/developmentboardsandkits/ecp5evaluationboard

Please do not forget to update Apio package to support this ECP-5 Evaluation Board

### CODE REVIEW

**Comment by cavearr** [comment]
Thanks Benitoss!

**Comment by ahnt** [comment]
When I change the board in Icestudio to ECP5 evaluation board (which I can select from the board menu) I get an "Unknown Board" error ... I guess I am overlooking something, please help! Cheers Arend

**Comment by benitoss** [comment]
> When I change the board in Icestudio to ECP5 evaluation board (which I can select from the board menu) I get an "Unknown Board" error ... I guess I am overlooking something, please help! Cheers Arend

Please do not forget to update Apio package to support this ECP-5 Evaluation Board
You have to install the last IceStudio => 8.1 and Apio 0.8  ( https://github.com/FPGAwars/apio/releases )

**Comment by cavearr** [comment]
Hi! Try @benitoss suggestions and in the same way you could install the latest WIP, more unenstable but with the latest features:

https://downloads.icestudio.io

**Pull request merged**
