### PR TITLE
UP5K boards support

### PR DESCRIPTION
**Pull request by mmicko**
Here are definition files for some of UP5K boards, will add iCEBreaker Bitsy when I get PCF.

Note that Upduino and Upduino 2 do not have dedicated CLK pin, it would need addition of internal CLK support in this case.

### CODE REVIEW

**Comment by Jesus89** [comment]
Thank you very much!

I have updated the base branch to `up5k` branch. I'll wait for the rest of the boards to merge this PR.

I'll think about the support for an internal CLK.

**Comment by mmicko** [comment]
Updated bitsy according to schematics, and did couple of more fixes.

**Comment by Jesus89** [comment]
Great. Thanks! :)

**Comment by sismoke** [comment]
when is the support for UP5K boards going to be released?

**Comment by esden** [comment]
Hey, I am just trying to use icestudio for icebreaker. I did not realize that the up5k related code is still in a separate branch. Is there a reason why this has not been merged into the main branch yet? What is still necessary so that the up5k boards can go into the main development branch?

Cheers and thanks for all the hard work. :)

**Pull request merged**
