### PR TITLE
Label Search implementation "first tests" OK

### PR DESCRIPTION
**Pull request by mSlider**
- Here are the the changes with the missing file in #568 PR!

Alex (mSlider)

### CODE REVIEW

**Comment by cavearr** [comment]
Thanks a lot!

**Comment by jojo535275** [comment]
Hola Alex,

On my first test of wip  0.8.1w202112230812,

Ctrl+F, in windows10,  does not open the pop-up window!

thanks

**Comment by jojo535275** [comment]
Oups Sorry, 
apparently the wip i tested was the one without the missing file.
i will let you now after the  test of the shortly coming wip !

**Comment by mSlider** [comment]
Hi @jojo535275,

If there are issues please let me know. It's a test version... so could be some case that I've not tested.

**Comment by jojo535275** [comment]
Hola Alex 
So this version works perfectly!

Little potential ideas of mods

-if the users is still holing down the mouse button  after the time you set (1sec), let the labels highlighted. And un-highlight  when the left mouse button is released. 
- a bit more complex to implement, draw a straight line between the output Label and all input labels.
this can help to quickly see that we have wrongly inserted two output babels for the same net.

But if you want to implement those do it after Christmas, Our body needs to have some time without computers, and maybe a bit with family ;-)

Thanks again for all the work you did for the community these days and have a good time!

**Pull request merged**
