### PR TITLE
Label-Finder upgrade v2.2

### PR DESCRIPTION
**Pull request by mSlider**
- Added Undo/Redo functions to label-Finder
- Added "Tab key" shortcut to show/hide replace "Label Finder" tab
- Fix in color selection boxes
- Fix Undo/Redo label colors functions
- Change InputLabel <=> OutputLabel in Toolbox to match actual Basic system convention

labelFinder_v2_2

### CODE REVIEW

**Comment by jojo535275** [comment]
Thanks Alex this looks perfect!
i will try it tonight.

Have a good day

**Comment by jojo535275** [comment]
Hola Alex, 

it works really well including the undo/redo feature !

Looking at the code i discovered that you even implemented the use of keyboard keys for few function (tab, left and right)  cool!

To have an "auto-find" triggered when we click on "case sensitive" or in "exact", i tried just adding at lines 1434 and 1445  your  function  findItems();
and it works fine.  if you want to add it !

I think we can say that this labelFinder function is now complete and a must have!

Thanks a lot again Alex.

Joaquim

**Comment by mSlider** [comment]
Hi @jojo535275 

- Good to implement the "auto-find" triggered in those cases!

Another issue I have encountered is with "label-buses" it makes something strange... I think I have to play with the regex definition to see if I can fix with that.

Apart of this, I think the labelFinder as you said is mostly complete!

Thanks jo!!!

**Comment by jojo535275** [comment]
Hello Alex,

Good find for the bus labels, i just tried and found (probably the same bug):
For a label rdy[9:0]
finding "rdy" and replacing by "rdt"
gives    rdt[9:0][9:0]

so, yes, [9:0] is doubled

As promised, just after this bug resolution i will pull request the translate mods!

Thanks!

Joaquim

**Comment by mSlider** [comment]
Hi @jojo535275 

I think I've fixed the label bus find/replace issue in this PR #580 and some minor other things.

If you want, when you try it if there is something we can continue commenting in the #580

@cavearr,
Hope the change in Toolbix open (Ctrl+T) instead of (Ctrl+space) is welcome, because when I was tried in mac the Meta+space is used for a system search function. I think Ctrl+T is more intuitive and unified to all platforms!

Any comment better in the PR #580.

Have a good evening!

Alex (mSlider)

**Pull request merged**
