### PR TITLE
Label Finder Upgrade + mods & fixes

### PR DESCRIPTION
**Pull request by mSlider**
Label Finder Upgrade:
- Added Preferences->Label Finder menu option (thanks to @jojo535275 )
- Added left/right keys shortcuts for faster navigation between matching labels
- Added match options: "Exact"-> " and "Case Sensitive"-> Aa
- Retractable advanced layout for replace functions 
- Now can replace "name" and "color" of matching labels
- The changes are permanent if save the file 

mods & fixes:
- Add title to Toolbox Basic
- Make toolbox Dragabble from title bar

### CODE REVIEW

**Comment by mSlider** [comment]
A screenshot with the new features of the Label Finder
labelFinder_v2

**Comment by cavearr** [comment]
Great Alex!

**Comment by jojo535275** [comment]
This looks beautiful Alex,

Congratulations! i will try it now!

Muchas gracias for these new year gift !

**Comment by jojo535275** [comment]
Hello guys,
So, i installed the executable on windows and also runned the appimage on linux buy i saw no difference compared to the previous wip ?

**Comment by mSlider** [comment]
@jojo535275, 
you are right, I've downladed the last WIP 0.8.1w202201021201 and seems like the isn't any of the last changed files.

Seems like the "autocompile" or some kind of program didn't include the last modified files...
May be @Obijuan or @cavearr knows what happen...

Regards!

And happy new year to all of you!

**Comment by cavearr** [comment]
Hi Guys! the WIP is being generating again, the code contains some "formal errors" i'm fixing and uploading again.

@mSlider @jojo535275 always before you do a pull request, execute locally:

npm run build  

with this command the executable, builds in your computer and if violates some standard code, you could fix before push.

In few minutes , executables will be generated!

**Pull request merged**
