### PR TITLE
PR745 One more translation code change, one more fix errors

### PR DESCRIPTION
**Pull request by TimRudy**

### CODE REVIEW

**Comment by cavearr** [comment]
Thanks and thanks again

**Comment by TimRudy** [comment]
Carlos should I put a note in the 0.9.2 release thread asking for
translators to look at their language, due to new functionality? I'm not
sure if it's OK to "reach out" or if anyone would notice such a message. I
want to link to the PRs I created for 3 or 4 languages. Thoughts?

**Comment by cavearr** [comment]
It seems like a very good idea to me, the translators until now have been spontaneous collaborators but I find it very interesting to motivate potential contributors in the translators to continue participating, review... For my part, it puts the message inviting collaboration, many times the community just needs a little push ;)

**Comment by TimRudy** [comment]
Perfect, I like your thinking :-)

**Comment by TimRudy** [comment]
That's it - Done translations and don't plan to do more myself! Development
branch should have "safe", error-free translations, hopefully no
embarrassing things, and that's the baseline. Let's see if people add more
later. Maybe I will be asked to change those 4 PRs from "Draft" status; if
so, no problem.

Thanks Charli, I'll be around, will fix some bugs later.

**Pull request merged**
