### PR TITLE
utils: Use shelljs.which to get the path for an executable

### PR DESCRIPTION
**Pull request by kiike**
This PR modifies the previous work on `utils.js`, adding a dependency for `shelljs` and using its `which` function so that we don't need to install `which` on Windows, for instance. Tested on Windows and Linux this time with only one Python installation. Feel free to disregard and close the PR if adding the dependency is not ideal.

### CODE REVIEW

**Comment by cavearr** [comment]
Thanks a lot @kiike ! i'm planning use nix for package distribution for wips binaries , your work will be very useful, if you are working in this way please comment us in the open thread https://github.com/FPGAwars/icestudio/issues/750

**Comment by kiike** [comment]
Thanks @cavearr for your review and merging the PR! I am part of a team (@jleightcap, @amerinor01, @imadnyc, @rcoeurjoly and me) that is actually bringing Icestudio to Nix and NixOS as sponsored work under the NLNet's NGI0 umbrella!

We've successfully repackaged the AppImage for Nix and NixOS, and were able to confirm successful operation with an Alhambra board in Nix on Ubuntu on top of WSL. In NixOS, the program seems to work fine although, we can't test interfacing with boards, as the two of us who use NixOS don't have boards to test.

Now we're in the process of packaging Icestudio (without AppImage) to have an alternative and more canonical way of installing the program. The abundance of comments and documentation in the project, along with your responsiveness make it a very good experience so far!

**Comment by cavearr** [comment]
Hi @kiike ! if i could help , tell me and i'll do very happy! is the package public now? i could test with several boards and in osx too.

Could be possible integrate nix package update into our CI process to automatically update package on updates on the stable branch and the development branch?

I don't know very well nix package, my first contact has been helping in the #755 issue and i'm falling in love with it.

Have you some public place where your team work on this to try to help you in it?

Thanks a lot to all of the team for support this!

**Comment by kiike** [comment]
> Hi @kiike ! if i could help , tell me and i'll do very happy! is the package public now? i could test with several boards and in osx too.

Thanks for the kind words! We definitely have some points we'd like to comment. We'll make issues/PRs for them I guess so that they can be tracked.

> Could be possible integrate nix package update into our CI process to automatically update package on updates on the stable branch and the development branch?

I see two artifacts. One is the nixpkgs package. Once we have a merged PR for the package we are doing, the package should update automatically and then get deployed after a manual review. The other artifact, which can exist in parallel, is a nix flake. That would allow you to do install development versions of the package. That is work that I think falls in scope with our sponsorship so I'll bring it up with the team! Having CI cache the results to avoid building will be awesome!

> I don't know very well nix package, my first contact has been helping in the https://github.com/FPGAwars/icestudio/pull/755 issue and i'm falling in love with it.

> Have you some public place where your team work on this to try to help you in it?

Today we finished a non-appimage version of the package, so now we build Icestudio from source. We still have some steps to do, like cleanup and documenting, self-updating, etc, but there is a working version at https://github.com/jleightcap/nixpkgs/tree/fern/icestudio/pkgs/by-name/ic/icestudio

If you have an OS X system, trying out that package will be great. Let us know if you need help getting that set up!
 
> Thanks a lot to all of the team for support this!

:heart:

**Pull request merged**
