### PR TITLE
Label-Finder update 2.3 fixed

### PR DESCRIPTION
**Pull request by mSlider**
- Reworked custom "color-dropdown" to add coloured badges next to the color's names
- Added new color -> "LightGray"

Label_Finder_v2_3

### CODE REVIEW

**Comment by cavearr** [comment]
Great improvement!

**Comment by jojo535275** [comment]
Yes looks beautiful Alex!

I just pull requested the translation for the texts!
I did not found short translations for  "new name" an "new color".   "Nuevo nombre" or "Nueva Color" are too big! So i let the english words (same for french translation).

Thanks to you!
And thank Carlos for the "Basic" menu removal !

Have a good evening!

**Comment by mSlider** [comment]
Hi Jo,

If you want I can make the Label-Finder a little wider for accommodate "nuevo nombre" y " nuevo color" translations.

At the moment I'm gonna work with "remake" the color-dropdown for the "input.label" and "output.label" panel.

Thanks!

**Comment by jojo535275** [comment]
Well this is really a detail, but i just pull request it with "nuevo nombre" y " nuevo color"!

Like this you can adapt the size to it!  But if it is to difficult to fit, don't loose your time we can just revert this last PR i did !

Thanks

**Comment by mSlider** [comment]
Hi Jo,

I've pulled a new mod #585 with the reworked color-dropdown menu un label forms.

Next I'll modify the width of the "label-Finder", today has not given me time ;-P

**Comment by cavearr** [comment]
Ja,ja,ja, @mSlider good work! and dont worry, advance when you could!

**Comment by jojo535275** [comment]
Good Alex,

Well.... ok,....  I give you the right to go to bed now  :-)))

Thanks and Good night guys.

**Pull request merged**
